version: '3.9'

services:
  backend:
    container_name: resource-apps-backend-staging
    image: biggiefrye45/resource-apps-backend:staging
    env_file:
      - .env
    networks:
      - resource_apps_default
    ports:
      - 8899:5001
    volumes:
      - /docker/appdata/resource-apps-backend-staging/backend:/app
    restart: unless-stopped

networks:
  resource_apps_default:
    external: true
