name: Docker Hub Production Deployment
run-name: ${{ github.actor}} Pushing to production

on:
  push:
    branches: [production]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login into Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/resource-apps-backend:testing

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Manual Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN}}
          approvers: 'ianfrye0818'
          minimum-approvals: 1
          issue-title: 'Deploying for production'
          issue-body: 'Approve this issue to deploy to production'
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: 'yes,okay,approve'
          additional-denied-words: 'no,deny'
          timeout-minutes: 30
